// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vipipaashdzdjbhtzjgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpcGlwYWFzaGR6ZGpiaHR6amdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MjMyMDksImV4cCI6MjA2NzA5OTIwOX0.k-NfIV5bRqrs2ym9vo1Kp69kLVukx-iGtT8-0HYGsms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});